### ISSUE TITLE
Bad build on PPPL

### ISSUE THREAD

**Issue by smithsp** [gafusion/harvest_client#3]
In `/p/atom/atom`, with environment:
```
module load intel
module load pathscale
module load openmpi/1.4.1
module load acml
module load netcdf/4.0.1
module load fftw/2.1.5
module load hdf5-serial/1.8.5
```
`make all PLATFORM=PPPL` fails with the message:
```
mpif90 -mod /p/atom/atom/gacode/modules -I /p/atom/atom/gacode/modules -vec-report0 -shared-intel -o tglf_mpi tglf_mpi.o tglf_lib.a /p/atom/atom/gacode/shared/harvest_client/libharvest.a /usr/pppl/intel/11-pkgs/acml-4.3.0/ifort64/lib/libacml.a /usr/pppl/intel/11-pkgs/openmpi-pkgs/fftw-2.1.5/lib/librfftw.a /usr/pppl/intel/11-pkgs/openmpi-pkgs/fftw-2.1.5/lib/libfftw.a /usr/pppl/intel/11-pkgs/acml-4.3.0/ifort64/lib/libimf.a 
/p/atom/atom/gacode/shared/harvest_client/libharvest.a(harvest_lib.o): In function `init_harvest':
/p/atom/atom/gacode/shared/harvest_client/harvest_lib.c:290: undefined reference to `memset.pathscale.opteron'
/p/atom/atom/gacode/shared/harvest_client/libharvest.a(harvest_lib.o): In function `harvest_send':
/p/atom/atom/gacode/shared/harvest_client/harvest_lib.c:332: undefined reference to `memset.pathscale.opteron'
/p/atom/atom/gacode/shared/harvest_client/harvest_lib.c:334: undefined reference to `memset.pathscale.opteron'
```

**Comment by orso82** [comment]
Was the library libharves.a created? I think it's a problem with the linking to the library...

There was a similar issue on the MIT LOKI cluster, but I do not know if it got resolved. Maybe @jcandy knows.

@logan-nc how did you compile the harvest_client at PPPL?

**Comment by logan-nc** [comment]
I compile it with DCON,IPEC, and PENT just fine. See /p/gpec/users/nlogan/gpec... 

I've use gfortran and lff95 mostly, and I thought intel worked too. I think you have to build the library with the same compiler you are using to link to it though, so if you are just linking to someone elses build you might be running a different compiler than they used. For a global build, you would need a "module load harvest" that sets HARVESTHOME to different paths based on the loaded compiler right?

**Comment by smithsp** [comment]
My problem was that I needed to add `CC=mpicc` to the `make.inc.PPPL` file in the GACODE repo.
